 Vae model:  camcan_400_Aug_2_100  NN model:  train_1subj_app1_1250
Using device: cuda:0
Loading train set for subj
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579022071458/work/aten/src/THCUNN/generic/LeakyReLU.cu line=29 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "restore_MAP_NN.py", line 78, in <module>
    device, riter, step_rate)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/utils/threshold.py", line 365, in compute_threshold_subj
    recon_batch, z_mean, z_cov, res = vae_model(scan)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 53, in forward
    mu, logvar, res = self.encode(x)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 32, in encode
    h = self.encoder(x)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 559, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/functional.py", line 1063, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /opt/conda/conda-bld/pytorch_1579022071458/work/aten/src/THCUNN/generic/LeakyReLU.cu:29
