 Vae model:  camcan_400_Aug_2_100  NN model:  train_restore_120
Using device: cuda:0
0.5
0.0
Loading test set for subj
Subject  Brats17_CBICA_AMH_1_t2_unbiased.nii.gz  Number of Slices:  140
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
0.33844132593421594 0.0005135680780458104
0.315830662148554 0.00044865098406232326
0.31142498935387036 0.0004530023352503654
0.3223027688550669 0.0004027347264231767
0.30985199336297986 0.0005264708446094335
AUC :  0.9001086397000477
DCS:  0.0
0.02
Loading test set for subj
Subject  Brats17_TCIA_645_1_t2_unbiased.nii.gz  Number of Slices:  134
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
0.2890028553012299 0.0010194339494162615
0.29875505008707953 0.00033674688071031486
0.31084908661366567 0.0005119171670709948
Traceback (most recent call last):
  File "restore_MAP_NN.py", line 126, in <module>
    restored_batch = run_map_NN(scan, decoded_mu, net, vae_model, riter, device, writer, step_size=step_rate)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/restoration.py", line 58, in run_map_NN
    __, z_mean, z_cov, __ = vae_model(img_ano.unsqueeze(1).double())
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 55, in forward
    return self.decode(z), mu, logvar, res
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 40, in decode
    z = self.decoder(z)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 559, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/functional.py", line 1063, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 10.92 GiB total capacity; 10.28 GiB already allocated; 11.56 MiB free; 10.38 GiB reserved in total by PyTorch)
