Name:  train_teacher_1 Lr_rate:  0.001 Use Teacher:  True  Riter:  200  Subjs:  5
Using device: cuda:0
['Brats17_CBICA_APR_1_t2_unbiased.nii.gz', 'Brats17_TCIA_218_1_t2_unbiased.nii.gz', 'Brats17_CBICA_AAP_1_t2_unbiased.nii.gz', 'Brats17_TCIA_409_1_t2_unbiased.nii.gz']
validation subject ['Brats17_TCIA_231_1_t2_unbiased.nii.gz']
Loading train set for subj
Subject  Brats17_CBICA_APR_1_t2_unbiased.nii.gz  Number of Slices:  137
Traceback (most recent call last):
  File "train_restore_MAP_NN.py", line 148, in <module>
    else:
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/restoration.py", line 239, in train_run_map_NN_teacher
    dice_loss_teacher.backward()
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
